---
config:
  theme: default
---

erDiagram

IMAGES {
  int id PK
  string path
  string preprocessed_path
  json metadata
  timestamp created_at
  string status
}

MASKS {
  int id PK
  int image_id FK
  string annotator
  json annotation_data
  timestamp created_at
  string type
}

TILES {
  int id PK
  int image_id FK
  int row
  int col
  string tile_path
  string mask_path
  int masks_id FK
  string status
  timestamp created_at
}


MODELS {
  int id PK
  string type
  string version
  string path
  int trained_on FK
  json metrics
  timestamp created_at
}

PREDICTIONS {
  int id PK
  int tile_id FK
  int model_id FK
  json prediction
  float iou
  float rmse
  timestamp created_at
  string status
}

VECTOR_MASKS {
  int id PK
  int tile_id FK
  json vector_data
  float iou
  timestamp created_at
}

GIS_LAYERS {
  int id PK
  int vector_mask_id FK
  string layer_name
  json metadata
  timestamp created_at
}

STORAGE_FILES {
  int id PK
  int tile_id FK
  string file_type
  string path
  timestamp created_at
  json metadata
}

%% Связи между таблицами
IMAGES ||--o{ MASKS : ""
MASKS ||--o{ TILES : ""
IMAGES ||--o{ TILES : ""
MODELS ||--o{ PREDICTIONS : ""
TILES ||--o{ PREDICTIONS : ""
TILES ||--o{ VECTOR_MASKS : ""
VECTOR_MASKS ||--o{ GIS_LAYERS : ""
TILES ||--o{ STORAGE_FILES : ""
